# Generated by Django 2.1.4 on 2019-01-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("homevisit", "0003_faq")]

    operations = [
        migrations.RenameField(
            model_name="feedback", old_name="feedback", new_name="comment"
        ),
        migrations.AlterField(
            model_name="feedback",
            name="issue",
            field=models.CharField(
                choices=[
                    ("QUESTIONS", "I have some questions before I sign up"),
                    ("CANCEL", "I need to cancel or reschedule my existing meeting"),
                    ("SCHEDULING", "I'm having problems scheduling"),
                    ("GENERAL", "I have some general feedback"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="person", name="last_name", field=models.CharField(max_length=30)
        ),
    ]
