# Generated by Django 2.1.4 on 2019-01-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homevisit', '0004_feedback_field_renamed_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homevisit.Household'),
        ),
    ]
